# Generated by Django 4.2.4 on 2024-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangkokWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ts', models.DateTimeField()),
                ('last_updated', models.TimeField()),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=4)),
                ('feelslike_c', models.DecimalField(decimal_places=2, max_digits=4)),
                ('condition_text', models.CharField(max_length=300)),
                ('wind_kph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wind_dir', models.CharField(max_length=3)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cloud', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
