# Generated by Django 4.2.4 on 2024-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustnweatherapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangkokDust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pm1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pm2_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pm10', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
