# Generated by Django 4.2.4 on 2024-04-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dustnweatherapi', '0002_bangkokdust'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='bangkokdust',
            table_comment='bangkok_dust',
        ),
        migrations.AlterModelTableComment(
            name='bangkokweather',
            table_comment='bangkok_weather',
        ),
    ]
