# Generated by Django 4.2.4 on 2024-04-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dustnweatherapi', '0003_alter_bangkokdust_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='bangkokdust',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='bangkokweather',
            table_comment=None,
        ),
        migrations.AlterModelTable(
            name='bangkokdust',
            table='bangkok_dust',
        ),
        migrations.AlterModelTable(
            name='bangkokweather',
            table='bangkok_weather',
        ),
    ]
