# Generated by Django 4.2.4 on 2024-05-11 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustnweatherapi', '0005_remove_bangkokweather_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangkokdust',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 28, 44, 770964)),
        ),
        migrations.AddField(
            model_name='bangkokweather',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 28, 44, 769967)),
        ),
    ]
