# Generated by Django 4.2.4 on 2024-05-11 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustnweatherapi', '0006_bangkokdust_ts_bangkokweather_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangkokweather',
            name='feelslike_c',
        ),
        migrations.RemoveField(
            model_name='bangkokweather',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='bangkokweather',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='bangkokweather',
            name='lon',
        ),
        migrations.AlterField(
            model_name='bangkokdust',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 33, 11, 588014)),
        ),
        migrations.AlterField(
            model_name='bangkokweather',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 33, 11, 588014)),
        ),
    ]
