# Generated by Django 4.2.4 on 2024-05-11 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustnweatherapi', '0007_remove_bangkokweather_feelslike_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangkokdust',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 43, 56, 817147)),
        ),
        migrations.AlterField(
            model_name='bangkokweather',
            name='cloud',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bangkokweather',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bangkokweather',
            name='temp_c',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bangkokweather',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 20, 43, 56, 816149)),
        ),
        migrations.AlterField(
            model_name='bangkokweather',
            name='wind_kph',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
