# Generated by Django 4.2.4 on 2024-05-11 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dustnweatherapi', '0008_alter_bangkokdust_ts_alter_bangkokweather_cloud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangkokDustNWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('ts', models.DateTimeField(default=datetime.datetime(2024, 5, 11, 22, 27, 9, 638124))),
                ('pm1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pm2_5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pm10', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition_text', models.CharField(max_length=300)),
                ('wind_kph', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wind_dir', models.CharField(max_length=3)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cloud', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bangkok_dustnweather',
            },
        ),
        migrations.RemoveField(
            model_name='bangkokdust',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='bangkokdust',
            name='lon',
        ),
        migrations.AlterField(
            model_name='bangkokdust',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 22, 27, 9, 637126)),
        ),
        migrations.AlterField(
            model_name='bangkokweather',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 22, 27, 9, 637126)),
        ),
    ]
