# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DustShort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, location: str=None, pm2_5: float=None):  # noqa: E501
        """DustShort - a model defined in Swagger

        :param id: The id of this DustShort.  # noqa: E501
        :type id: int
        :param location: The location of this DustShort.  # noqa: E501
        :type location: str
        :param pm2_5: The pm2_5 of this DustShort.  # noqa: E501
        :type pm2_5: float
        """
        self.swagger_types = {
            'id': int,
            'location': str,
            'pm2_5': float
        }

        self.attribute_map = {
            'id': 'id',
            'location': 'location',
            'pm2_5': 'pm2_5'
        }
        self._id = id
        self._location = location
        self._pm2_5 = pm2_5

    @classmethod
    def from_dict(cls, dikt) -> 'DustShort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dustShort of this DustShort.  # noqa: E501
        :rtype: DustShort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this DustShort.


        :return: The id of this DustShort.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this DustShort.


        :param id: The id of this DustShort.
        :type id: int
        """

        self._id = id

    @property
    def location(self) -> str:
        """Gets the location of this DustShort.


        :return: The location of this DustShort.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this DustShort.


        :param location: The location of this DustShort.
        :type location: str
        """

        self._location = location

    @property
    def pm2_5(self) -> float:
        """Gets the pm2_5 of this DustShort.


        :return: The pm2_5 of this DustShort.
        :rtype: float
        """
        return self._pm2_5

    @pm2_5.setter
    def pm2_5(self, pm2_5: float):
        """Sets the pm2_5 of this DustShort.


        :param pm2_5: The pm2_5 of this DustShort.
        :type pm2_5: float
        """

        self._pm2_5 = pm2_5
