# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DustFull(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, ts: str=None, lat: float=None, lon: float=None, pm1: float=None, pm2_5: float=None, pm10: float=None, location: float=None):  # noqa: E501
        """DustFull - a model defined in Swagger

        :param id: The id of this DustFull.  # noqa: E501
        :type id: int
        :param ts: The ts of this DustFull.  # noqa: E501
        :type ts: str
        :param lat: The lat of this DustFull.  # noqa: E501
        :type lat: float
        :param lon: The lon of this DustFull.  # noqa: E501
        :type lon: float
        :param pm1: The pm1 of this DustFull.  # noqa: E501
        :type pm1: float
        :param pm2_5: The pm2_5 of this DustFull.  # noqa: E501
        :type pm2_5: float
        :param pm10: The pm10 of this DustFull.  # noqa: E501
        :type pm10: float
        :param location: The location of this DustFull.  # noqa: E501
        :type location: float
        """
        self.swagger_types = {
            'id': int,
            'ts': str,
            'lat': float,
            'lon': float,
            'pm1': float,
            'pm2_5': float,
            'pm10': float,
            'location': float
        }

        self.attribute_map = {
            'id': 'id',
            'ts': 'ts',
            'lat': 'lat',
            'lon': 'lon',
            'pm1': 'pm1',
            'pm2_5': 'pm2_5',
            'pm10': 'pm10',
            'location': 'location'
        }
        self._id = id
        self._ts = ts
        self._lat = lat
        self._lon = lon
        self._pm1 = pm1
        self._pm2_5 = pm2_5
        self._pm10 = pm10
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'DustFull':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dustFull of this DustFull.  # noqa: E501
        :rtype: DustFull
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this DustFull.


        :return: The id of this DustFull.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this DustFull.


        :param id: The id of this DustFull.
        :type id: int
        """

        self._id = id

    @property
    def ts(self) -> str:
        """Gets the ts of this DustFull.


        :return: The ts of this DustFull.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this DustFull.


        :param ts: The ts of this DustFull.
        :type ts: str
        """

        self._ts = ts

    @property
    def lat(self) -> float:
        """Gets the lat of this DustFull.


        :return: The lat of this DustFull.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this DustFull.


        :param lat: The lat of this DustFull.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this DustFull.


        :return: The lon of this DustFull.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this DustFull.


        :param lon: The lon of this DustFull.
        :type lon: float
        """

        self._lon = lon

    @property
    def pm1(self) -> float:
        """Gets the pm1 of this DustFull.


        :return: The pm1 of this DustFull.
        :rtype: float
        """
        return self._pm1

    @pm1.setter
    def pm1(self, pm1: float):
        """Sets the pm1 of this DustFull.


        :param pm1: The pm1 of this DustFull.
        :type pm1: float
        """

        self._pm1 = pm1

    @property
    def pm2_5(self) -> float:
        """Gets the pm2_5 of this DustFull.


        :return: The pm2_5 of this DustFull.
        :rtype: float
        """
        return self._pm2_5

    @pm2_5.setter
    def pm2_5(self, pm2_5: float):
        """Sets the pm2_5 of this DustFull.


        :param pm2_5: The pm2_5 of this DustFull.
        :type pm2_5: float
        """

        self._pm2_5 = pm2_5

    @property
    def pm10(self) -> float:
        """Gets the pm10 of this DustFull.


        :return: The pm10 of this DustFull.
        :rtype: float
        """
        return self._pm10

    @pm10.setter
    def pm10(self, pm10: float):
        """Sets the pm10 of this DustFull.


        :param pm10: The pm10 of this DustFull.
        :type pm10: float
        """

        self._pm10 = pm10

    @property
    def location(self) -> float:
        """Gets the location of this DustFull.


        :return: The location of this DustFull.
        :rtype: float
        """
        return self._location

    @location.setter
    def location(self, location: float):
        """Sets the location of this DustFull.


        :param location: The location of this DustFull.
        :type location: float
        """

        self._location = location
