# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WeatherShort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, ts: str=None, temp_c: float=None, wind_kph: float=None, humidity: float=None):  # noqa: E501
        """WeatherShort - a model defined in Swagger

        :param id: The id of this WeatherShort.  # noqa: E501
        :type id: int
        :param ts: The ts of this WeatherShort.  # noqa: E501
        :type ts: str
        :param temp_c: The temp_c of this WeatherShort.  # noqa: E501
        :type temp_c: float
        :param wind_kph: The wind_kph of this WeatherShort.  # noqa: E501
        :type wind_kph: float
        :param humidity: The humidity of this WeatherShort.  # noqa: E501
        :type humidity: float
        """
        self.swagger_types = {
            'id': int,
            'ts': str,
            'temp_c': float,
            'wind_kph': float,
            'humidity': float
        }

        self.attribute_map = {
            'id': 'id',
            'ts': 'ts',
            'temp_c': 'temp_c',
            'wind_kph': 'wind_kph',
            'humidity': 'humidity'
        }
        self._id = id
        self._ts = ts
        self._temp_c = temp_c
        self._wind_kph = wind_kph
        self._humidity = humidity

    @classmethod
    def from_dict(cls, dikt) -> 'WeatherShort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The weatherShort of this WeatherShort.  # noqa: E501
        :rtype: WeatherShort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this WeatherShort.


        :return: The id of this WeatherShort.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this WeatherShort.


        :param id: The id of this WeatherShort.
        :type id: int
        """

        self._id = id

    @property
    def ts(self) -> str:
        """Gets the ts of this WeatherShort.


        :return: The ts of this WeatherShort.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this WeatherShort.


        :param ts: The ts of this WeatherShort.
        :type ts: str
        """

        self._ts = ts

    @property
    def temp_c(self) -> float:
        """Gets the temp_c of this WeatherShort.


        :return: The temp_c of this WeatherShort.
        :rtype: float
        """
        return self._temp_c

    @temp_c.setter
    def temp_c(self, temp_c: float):
        """Sets the temp_c of this WeatherShort.


        :param temp_c: The temp_c of this WeatherShort.
        :type temp_c: float
        """

        self._temp_c = temp_c

    @property
    def wind_kph(self) -> float:
        """Gets the wind_kph of this WeatherShort.


        :return: The wind_kph of this WeatherShort.
        :rtype: float
        """
        return self._wind_kph

    @wind_kph.setter
    def wind_kph(self, wind_kph: float):
        """Sets the wind_kph of this WeatherShort.


        :param wind_kph: The wind_kph of this WeatherShort.
        :type wind_kph: float
        """

        self._wind_kph = wind_kph

    @property
    def humidity(self) -> float:
        """Gets the humidity of this WeatherShort.


        :return: The humidity of this WeatherShort.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this WeatherShort.


        :param humidity: The humidity of this WeatherShort.
        :type humidity: float
        """

        self._humidity = humidity
